__all__ = [
        "ALL_DETECTORS",
        "AD_DETECTORS",
        "WP_DETECTORS",
        "IAV_INNER_RADIUS",
        "IAV_OUTER_RADIUS",
        "IAV_INNER_HALF_HEIGHT",
        "IAV_OUTER_HALF_HEIGHT",
        "OAV_INNER_RADIUS",
        "OAV_OUTER_RADIUS",
        "OAV_INNER_HALF_HEIGHT",
        "OAV_OUTER_HALF_HEIGHT",
        ]
ALL_DETECTORS = [0, 1, 2, 3, 4, 5, 6, 7, 8]
AD_DETECTORS = [1, 2, 3, 4]
WP_DETECTORS = [5, 6]

IAV_INNER_RADIUS = 1540
IAV_OUTER_RADIUS = 1550
IAV_INNER_HALF_HEIGHT = IAV_INNER_RADIUS
IAV_OUTER_HALF_HEIGHT = IAV_OUTER_RADIUS
OAV_INNER_RADIUS = 3982
OAV_OUTER_RADIUS = 4000
OAV_INNER_HALF_HEIGHT = OAV_INNER_RADIUS
OAV_OUTER_HALF_HEIGHT = OAV_OUTER_RADIUS
