python fit_delayed.py --site 1 --ad 1 --source nominal $SCRATCH/dyb30/processed_adtime/EH1/sub_nominal_ad1/sub_ad1.root -o fit_nominal_eh1_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 1 --ad 2 --source nominal $SCRATCH/dyb30/processed_adtime/EH1/sub_nominal_ad2/sub_ad2.root -o fit_nominal_eh1_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 2 --ad 1 --source nominal $SCRATCH/dyb30/processed_adtime/EH2/sub_nominal_ad1/sub_ad1.root -o fit_nominal_eh2_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 2 --ad 2 --source nominal $SCRATCH/dyb30/processed_adtime/EH2/sub_nominal_ad2/sub_ad2.root -o fit_nominal_eh2_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 1 --source nominal $SCRATCH/dyb30/processed_adtime/EH3/sub_nominal_ad1/sub_ad1.root -o fit_nominal_eh3_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 2 --source nominal $SCRATCH/dyb30/processed_adtime/EH3/sub_nominal_ad2/sub_ad2.root -o fit_nominal_eh3_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 3 --source nominal $SCRATCH/dyb30/processed_adtime/EH3/sub_nominal_ad3/sub_ad3.root -o fit_nominal_eh3_ad3.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 4 --source nominal $SCRATCH/dyb30/processed_adtime/EH3/sub_nominal_ad4/sub_ad4.root -o fit_nominal_eh3_ad4.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 1 --ad 1 --source adtime $SCRATCH/dyb30/processed_adtime/EH1/sub_using_adtime_ad1/sub_ad1.root -o fit_adtime_eh1_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 1 --ad 2 --source adtime $SCRATCH/dyb30/processed_adtime/EH1/sub_using_adtime_ad2/sub_ad2.root -o fit_adtime_eh1_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 2 --ad 1 --source adtime $SCRATCH/dyb30/processed_adtime/EH2/sub_using_adtime_ad1/sub_ad1.root -o fit_adtime_eh2_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 2 --ad 2 --source adtime $SCRATCH/dyb30/processed_adtime/EH2/sub_using_adtime_ad2/sub_ad2.root -o fit_adtime_eh2_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 1 --source adtime $SCRATCH/dyb30/processed_adtime/EH3/sub_using_adtime_ad1/sub_ad1.root -o fit_adtime_eh3_ad1.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 2 --source adtime $SCRATCH/dyb30/processed_adtime/EH3/sub_using_adtime_ad2/sub_ad2.root -o fit_adtime_eh3_ad2.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 3 --source adtime $SCRATCH/dyb30/processed_adtime/EH3/sub_using_adtime_ad3/sub_ad3.root -o fit_adtime_eh3_ad3.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
python fit_delayed.py --site 3 --ad 4 --source adtime $SCRATCH/dyb30/processed_adtime/EH3/sub_using_adtime_ad4/sub_ad4.root -o fit_adtime_eh3_ad4.pdf --update-db $SCRATCH/dyb30/adtime_dt_eff_study.db
